<?php

namespace Database\Seeders;

use App\Jobs\FetchChannelStatisticsJob;
use App\Models\Channel;
use App\Models\Topic;
use Faker\Factory;
use Illuminate\Database\Seeder;
use Str;

class ChannelSeeder extends Seeder
{
    public function run(): void
    {
        $topics = Topic::all();
        $channels = array(
            0 => array('GPT | ChatGPT | Midjourney — GPTMain News', '@GPTMainNews'),
            1 => array('Милорд', '@milord_q'),
            2 => array('GPT4Telegram | AI Community', '@gpt4telegram'),
            3 => array('Эксплойт', '@exploitex'),
            4 => array('Wylsacom Red', '@Wylsared'),
            5 => array('Romancev768', '@Romancev768'),
            6 => array('1337', '@chatgpt3'),
            7 => array('Бэкдор', '@whackdoor'),
            8 => array('Техномотель', '@technomotel'),
            9 => array('concertzaal', '@concertzaal'),
            10 => array('Цифровой Журнал | IT, ChatGPT', '@cjournal_neyroseti'),
            11 => array('Rozetked', '@rozetked'),
            12 => array('Hi, AI! | нейросети', '@hiaimedia'),
            13 => array('Habr Media', '@habr_media'),
            14 => array('Hitech', '@NewHiTech9'),
            15 => array('Не баг, а фича', '@bugfeature'),
            16 => array('в IT и выйти', '@encryptedch'),
            17 => array('Рестарт', '@remedia'),
            18 => array('Код Дурова', '@d_code'),
            19 => array('SteosVoice News', '@steosvoice'),
            20 => array('PROTechnology', '@PROTechnology_news'),
            21 => array('ИИшница: IT, ChatGPT, Midjourney', '@GPT4_5_4_NEYROSETY'),
            22 => array('Не баг, а фича', '@bugnotfeature'),
            23 => array('Диджитальная | IT, ChatGPT', '@digital_gpt4_neyroseti'),
            24 => array('Технологии | Нейросети | Боты', '@aiaiai'),
            25 => array('GGWP', '@GGWP_NewsChannel'),
            26 => array('1С Плюс', '@Lutshie_Kursy_1C'),
            27 => array('GigaChat', '@official_gigachat'),
            28 => array('Минцифры России', '@mintsifry'),
            29 => array('Нейродвиж', '@neuraldvig'),
            30 => array('ChatGPT — Нейросети', '@gpt_chat'),
            31 => array('Прокачай Мозг: Айти, Тренды, Технологии', '@iPumpBrain'),
            32 => array('CodeCamp', '@codecamp'),
            33 => array('Fanton RU', '@fanton_nft_ru'),
            34 => array('808', '@rbtshki'),
            35 => array('ChatGPT 4.0 & [🅼🅹] | Bot News', '@ChatGPT_BotNews'),
            36 => array('Яндекс', '@yandex'),
            37 => array('Книги для программистов', '@progbook'),
            38 => array('Новости безопасности от YouFast VPN™', '@YouFastVPN'),
            39 => array('Programmer & IT Memes', '@itmemes'),
            40 => array('GPT News | chatGPT | OpenAI', '@gpt_news'),
            41 => array('Фон', '@fon_tech'),
            42 => array('ТЕХНО: Яндекс про технологии', '@techno_yandex'),
            43 => array('Neuronbo', '@neuronbo'),
            44 => array('Джейпег Малевича', '@malepeg'),
            45 => array('Нажми Enter | Тренды, IT и бизнес', '@PushEnter'),
            46 => array('Dosug', '@dosugchannel'),
            47 => array('Chad AI | Все нейросети в одной', '@chadgpt_ru'),
            48 => array('Pochinka_blog', '@pochinka'),
            49 => array('Apple News', '@apple_tg'),
            50 => array('Social Engineering', '@Social_engineering'),
            51 => array('Мой Компьютер', '@mknewsru'),
            52 => array('Amnezia VPN Новости', '@amnezia_vpn_news_ru'),
            53 => array('КиберХаб - IT и Нейросети', '@kyberhub'),
            54 => array('Обзор Нейросетей', '@obzor_neirosetei'),
            55 => array('М.Видео | Эльдорадо', '@mvideoandeldorado'),
            56 => array('TechGPT [🅽 🅴 🆆 🆂] 🤖', '@TechGPTNews'),
            57 => array('EDYA GPT NEWS', '@edya_robot'),
            58 => array('Android Club', '@androidclubnik'),
            59 => array('Midjourney Креативы', '@midjourney_home'),
            60 => array('NeuroADEPT', '@neuroadepts'),
            61 => array('Нейросети & Технологии | DeepTech', '@DeepTechNET'),
            62 => array('Как приручить единорога', '@edinorog_q'),
            63 => array('StarLine Телематика. Новости и Обновления', '@starline_channel'),
            64 => array('GeekNeural: IT & Нейросети', '@geekneural'),
            65 => array('Илон Маск / IT blog', '@Elon_Musk_Tesla_Motors'),
            66 => array('Lifegoodd', '@lifegoodd1'),
            67 => array('SMART ZONE', '@SmartZoneZ'),
            68 => array('addmeto', '@addmeto'),
            69 => array('Samsung Russia', '@SamsungRussia'),
            70 => array('Python School', '@PythonAA'),
            71 => array('Алиса х Около Яндекс Станции', '@alice_yndx'),
            72 => array('Взгляд изнутри на IT', '@iznytri'),
            73 => array('GPT-4 Community', '@gpt4_tg'),
            74 => array('Троянский конь | IT, технологии', '@trojan_anonym'),
            75 => array('2ГИС', '@twogis'),
            76 => array('NewsNet | Нейросети', '@aitgru'),
            77 => array('LAMERLAND - overbafer1', '@overlamer1'),
            78 => array('ChatGPTBot Info', '@UnlimGPTBot'),
            79 => array('Этичный Хакер', '@hack_less'),
            80 => array('Web3', '@famweb3'),
            81 => array('Нейро (Midjourney)', '@neuro_code'),
            82 => array('Айден Стор - объявления от проверенных продавцов. Б/У и новая техника. Гарантия. Доставка по всей России.', '@ideniphonerf'),
            83 => array('Библиотека программиста | программирование, кодинг, разработка', '@proglibrary'),
            84 => array('Типичный программист', '@tproger'),
            85 => array('Илон Маск | Elon Musk', '@elonmusk_ru'),
            86 => array('Отдел К: IT-технологии, кибербезопасность', '@cyber_cabb'),
            87 => array('ЖЕЛЕЗНЫЙ', '@ironmanexpress'),
            88 => array('Хауди Хо - IT юмор, жизнь программиста', '@howdyho_official'),
            89 => array('Droider', '@droidergram'),
            90 => array('Хабр', '@habr_com'),
            91 => array('ITeach', '@iteach_ru'),
            92 => array('LEFT JOIN', '@leftjoin'),
            93 => array('Блохи в свитере', '@cyberfreek'),
            94 => array('Python обучающий', '@pythonist24'),
            95 => array('NOP::Nuances of Programming', '@nuancesprog'),
            96 => array('Fosters PC', '@FostersNews'),
            97 => array('Джарвис Ньюс | Нейросети', '@JarvisNew'),
            98 => array('УЛЬТРА IT', '@ultraPK'),
            99 => array('Нейросети: новости, обзоры, рейтинги', '@neirosetblog'),
            100 => array('Sacred Software 🔐', '@sacredsoftware'),
            101 => array('ChatGPT 4.0 | Канал Бота', '@ChatGPT_General_RU'),
            102 => array('AI Insider', '@ai_ins'),
            103 => array('Programmer memes', '@programmer_memes'),
            104 => array('[netstalkers]', '@netstalkers'),
            105 => array('PROAI', '@pro_ai_news'),
            106 => array('ITcour | Уроки программирования', '@itcour1'),
            107 => array('Чёрный Треугольник', '@black_triangle_tg'),
            108 => array('AI Masterminds', '@aimasterminds'),
            109 => array('Machinelearning', '@ai_machinelearning_big_data'),
            110 => array('Телега РОМАНЫЧА', '@telegaromanycha'),
            111 => array('RamCode', '@ramzan'),
            112 => array('IT Юмор', '@ithumor'),
            113 => array('Life-Hack - Хакинг / Хакер / Linux', '@haccking'),
            114 => array('ChatGPT | Нейро News', '@chatgpt_neiro_news'),
            115 => array('Журнал «Код»', '@thecodemedia'),
            116 => array('CyberYozh', '@cyberyozh_official'),
            117 => array('realme Russia', '@realmerussia'),
            118 => array('[PYTHON:TODAY]', '@python2day'),
            119 => array('PRO | Нейросети', '@pro_neiroset'),
            120 => array('Нейросеть | Боты 🤖', '@chatgpt_main'),
            121 => array('Stardust🚀', '@hitechnoligy'),
            122 => array('Хакер Free', '@hacker_frei'),
            123 => array('involta - технологии, наука, будущее, IT, интернет!', '@involta'),
            124 => array('СЯО, СЭР!', '@SyaoSir'),
            125 => array('RealTech', '@RealTechru'),
            126 => array('GPTTG | Новости | ChatGPT', '@Aidalle3'),
            127 => array('IT — это просто', '@IT_ABC'),
            128 => array('Магия нейросетей | Gemini, LLaMA, ChatGPT, Claude', '@NeuralMagic_official'),
            129 => array('The Next Level', '@the_next_leveI'),
            130 => array('SecurityLab.ru', '@SecLabNews'),
            131 => array('Python Academy', '@python_academy'),
            132 => array('Windows Community', '@wind_community'),
            133 => array('Роман Сакутин', '@sakutin_csharp'),
            134 => array('iPhones.ru', '@iphonesru'),
            135 => array('Pro IT 👨‍💻', '@ITshnikPro'),
            136 => array('Книги для программистов', '@bfbook'),
            137 => array('Айтишник | Апи | Технологии', '@atishnik'),
            138 => array('Исходный код', '@source_code'),
            139 => array('PRO AI | ПОЛЕЗНЫЙ СОФТ | НОВОСТИ', '@pro_ai_official'),
            140 => array('DevOps community for love', '@devopsforlove'),
            141 => array('Системный и Бизнес-анализ', '@ba_sa_analytics'),
            142 => array('restore:', '@restore_ru'),
            143 => array('ЧАТ GPT | IT | НЕЙРОСЕТИ', '@gpt4turbo'),
            144 => array('КиберПанк | Технологии Будущего | Technology', '@technology_future_cyberpunk'),
            145 => array('[404] — программирование', '@procode404'),
            146 => array('ЗаТелеком 🌐', '@zatelecom'),
            147 => array('Кладовая книг | IT', '@kladovaya_knig'),
            148 => array('Python Hacks', '@python_secrets'),
            149 => array('TechSparks', '@techsparks'),
            150 => array('Секреты аналитики | Data Science, BI, Tableau', '@analytics_secrets'),
            151 => array('Интернет-Розыск I OSINT I Киберрасследования', '@irozysk'),
            152 => array('Команды (Shortcuts)', '@iOSshortcut'),
            153 => array('ГлавХак', '@glav_hack'),
            154 => array('Терабит: айти технологии', '@tbite'),
            155 => array('hitvpn_blog', '@hitvpn_news'),
            156 => array('OSINT CLUB', '@osint_club_channel'),
            157 => array('эйай ньюз', '@ai_newz'),
            158 => array('Мир нейросетей - новости, обучение и заработок', '@pro_ai_novosti'),
            159 => array('ИРБ - работаем вместе!', '@irb_uik'),
            160 => array('Open Source', '@open_source_friend'),
            161 => array('ChatGPT | Midjourney | Нейросети', '@gpt3ru'),
            162 => array('Хайтек+', '@htech_plus'),
            163 => array('Программирование | книги', '@it_boooks'),
            164 => array('Букич IT', '@booki47'),
            165 => array('IT Repaсkers 🖥Программы и игры для ПК', '@PC_Repackers'),
            166 => array('Open IT | Программирование', '@openit_tg'),
            167 => array('Авито Недвижимость', '@avito_re_pro'),
            168 => array('Комп для чайника', '@pcTeapot'),
            169 => array('Mobiltelefon.ru | Новости и Обзоры', '@mobiltelefonru'),
            170 => array('Книги для программистов (reserved)', '@progbook2'),
            171 => array('Samsung - 1Galaxy', '@samsung1galaxy'),
            172 => array('Грокс', '@groks'),
            173 => array('Технопроходцы', '@technodrifters'),
            174 => array('MASHNEWS | Новости Промышленности', '@news_engineering'),
            175 => array('Neural Shit', '@NeuralShit'),
            176 => array('Neural Machine', '@neuralmachine'),
            177 => array('Chad GPT | Нейросети', '@AI_Chad'),
            178 => array('Rozetked Live', '@rozetkedlive'),
            179 => array('XOR', '@xor_journal'),
            180 => array('Сиолошная', '@seeallochnaya'),
            181 => array('The ExtremeCode Times', '@extremecode'),
            182 => array('IT и СОРМ', '@itsorm'),
            183 => array('Python Books. Книги по питону', '@pythonbooks'),
            184 => array('Python/ django', '@pythonl'),
            185 => array('Unity GameDev Программирование', '@unity_gamedev_unreal'),
            186 => array('KLOKTUN | Разработка и дизайн мобильных приложений', '@kloktun'),
            187 => array('Библиотека питониста | Python, Django, Flask', '@pyproglib'),
            188 => array('Python и 1000 программ', '@py_1000_prog'),
            189 => array('Google™', '@GooogleTM'),
            190 => array('TECNO Россия', '@tecnorussia'),
            191 => array('GPT AI BOT | News', '@gptchat_bot_news'),
            192 => array('Дипфейкер: нейросети, IT, технологии', '@deep_fake_bot_news'),
            193 => array('Интерсвязь', '@intersvyaz'),
            194 => array('НОВОСТИ APPLE', '@inewsapple'),
            195 => array('Solver Network | Channel', '@solver_network'),
            196 => array('Senior Python Developer', '@seniorpy'),
            197 => array('∏ρØƒuñçτØρ Øπτµç∑ | 👁‍🗨››››', '@profunctor_io'),
            198 => array('Крипта | ИИ Скруджа', '@ii_crypta'),
            199 => array('Porscode | CMD', '@porscode_tg'),
            200 => array('NEIT', '@Not_lt'),
            201 => array('ХАКЕРСПЕЙС', '@hackerspace_ru'),
            202 => array('Нейроновости', '@neuranews'),
            203 => array('Айфон Джобса', '@iPhoneJobs'),
            204 => array('Ромашка', '@PomaIIIka_13'),
            205 => array('Ulbi TV - fullstack разработка на JavaScript', '@ulbi_tv'),
            206 => array('PulseGPT: Новости', '@Pulse_GPT'),
            207 => array('Digital Доктор', '@tlgdoc'),
            208 => array('Яндекс Реклама', '@YANtech'),
            209 => array('ChatGPT-4 Work', '@chatgpt4_work'),
            210 => array('МегаФон', '@megafon_online'),
            211 => array('BZD • Книги для программистов', '@bzd_channel'),
            212 => array('Программирование с нуля', '@begincode'),
            213 => array('WhatsApp-Plus (Rezvan)', '@gbwamod'),
            214 => array('Айтишка - Digital & IT', '@ITtishka'),
            215 => array('Neural Brain - Нейросети', '@neural_braining'),
            216 => array('Пекашечка', '@MyPEKA'),
            217 => array('Сайтодел | GitHub, Верстка, Сайты, FullStack', '@sitodel'),
            218 => array('Upscale Tech', '@upscale_tech'),
            219 => array('Пекин Близко 🇨🇳', '@pekinblizko'),
            220 => array('SecAtor', '@true_secator'),
            221 => array('Искусственный интеллект. Высокие технологии', '@vistehno'),
            222 => array('"О ТОМ О СЁМ" о Xiaomi, Android и Технике', '@otomosem'),
            223 => array('Погромист', '@pogromist_it'),
            224 => array('Frontender\'s notes [ru]', '@frontendnoteschannel_ru'),
            225 => array('infosec', '@it_secur'),
            226 => array('Colibri | ИИ боты', '@Colibri_bots'),
            227 => array('UX Live 🔥', '@uxlive'),
            228 => array('TryChatGPT.ru GPT | ChatGPT | IT | Нейросети', '@chatgpt_try'),
            229 => array('TheBox📱', '@TelegaTheBox'),
            230 => array('AppleTheme', '@AppleThemeYouTube'),
            231 => array('BEZ.PROVODOV174 | Копии Apple №1.', '@Bezprovodov174'),
            232 => array('Умный журнал | Наука | Технологии', '@magazine_peace'),
            233 => array('Apple* Android * Mi', '@toptehnikavdom'),
            234 => array('Новости IT | Мир Программиста', '@mir_programmer'),
            235 => array('Серьезный тестировщик 🐞', '@serious_tester'),
            236 => array('CMD | IT', '@cmd_it'),
            237 => array('РоскомнадZор', '@rkn_tg'),
            238 => array('Нейросетошная | ChatGPT', '@neural_set'),
            239 => array('Анализ данных (Data analysis)', '@data_analysis_ml'),
            240 => array('Selectel Newsfeed', '@Selectel'),
            241 => array('IT Pirate | Back-end, Front-end, Design, Python, Java, C++', '@it_pirate_tg'),
            242 => array('Поколение Python 🐍', '@pygen_ru'),
            243 => array('Технологии | Новшества', '@Novie_tehno'),
            244 => array('IT STAND', '@ITSTAND_ORG'),
            245 => array('Программист * Все о компьютерах', '@itsupergeniy'),
            246 => array('Обзоры IT Новинок и Исследований', '@issledovanie_it'),
            247 => array('Тестировщик от бога', '@godoftesting'),
            248 => array('Новости в Мире IT', '@mir_it_novost'),
            249 => array('MD Says', '@mdsays'),
            250 => array('Codeby Pentest', '@codeby_sec'),
            251 => array('notebook-31', '@vnotebook31'),
            252 => array('LUX CODE | Нейросети, IT новости', '@lux_code'),
            253 => array('Demin’s Lounge', '@deminslounge'),
            254 => array('OSINT mindset', '@osint_mindset'),
            255 => array('О Железе. Новости ПК и Смартфонов', '@pk_smartphone'),
            256 => array('China Gadgets', '@chinagadgetsofficial'),
            257 => array('Tehnobzor: IT Технологии', '@Tehnobzor_it'),
            258 => array('4PDA', '@real4pda'),
            259 => array('Голос Маньяка', '@maniacvoice'),
            260 => array('Советы Айти', '@it_soveti'),
            261 => array('квазар в космосе', '@qwazaree'),
            262 => array('Базы данных | Access, SQL, Big Data', '@databases_secrets'),
            263 => array('Кибербезопасность|Интернет', '@it_imba'),
            264 => array('Alek OS', '@Alek_OS'),
            265 => array('Russian OSINT', '@Russian_OSINT'),
            266 => array('Полка Разработчика', '@developer_shelf'),
            267 => array('Регард', '@regardru'),
            269 => array('ЧЕСТНЫЙ БЛОГ', '@chestniyblog'),
            270 => array('Популярная механика', '@Popmeh'),
            271 => array('Korablikvideo | ChatGPT', '@korablikvideo'),
            272 => array('Skolkovo LIVE', '@skolkovolive'),
            273 => array('ТехноМакс: Максим Багаев', '@Tehnomaks'),
            274 => array('PRO Hi-Tech', '@prohitec'),
            275 => array('Java библиотека', '@javalib'),
            276 => array('LoneCoder / Private', '@Lonecoderdeanon'),
        );

        $channelsCount = count($channels);
        $channelsPerTopic = 6;

        foreach ($topics as $topic) {
            // Calculate the starting index for channels for this topic
            $startIndex = ($topic->id - 1) * $channelsPerTopic;

            // Loop through channels for this topic
            for ($i = 0; $i < $channelsPerTopic; $i++) {
                // Calculate the index for the current channel
                $index = ($startIndex + $i) % $channelsCount;

                $channel = $channels[$index];

                $url = $channel[1];
                $slug = $url . '-' . $topic->id;

                $createdChannel = Channel::factory()->create([
                    'topic_id' => $topic->id,
                    'channel_name' => $channel[0],
                    'url' => $url,
                    'slug' => $slug
                ]);

                FetchChannelStatisticsJob::dispatch($createdChannel);
            }
        }
    }
}
